#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# 현재 브랜치 이름 가져오기
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# dev나 master 브랜치로의 직접 push 방지
# if [ "$BRANCH_NAME" = "dev" ] || [ "$BRANCH_NAME" = "master" ]; then
#   echo "\033[1;31mError: Direct push to $BRANCH_NAME branch is not allowed.\033[0m"
#   echo "\033[1;33mPlease create a pull request instead.\033[0m"
#   exit 1
# fi

# 푸시하기 전에 빌드를 검증합니다
echo "빌드 검증 중..."
npm install
npm run build 